language: python
python:
  - "3.6"
dist: trusty
sudo: false

services:
  - postgresql

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libpq-dev

install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --system --dev
#  - npm install
#  - npm run build

before_script:
  - psql -c 'CREATE DATABASE jarr_test;' -U postgres
  - echo '{"jarr_testing":true,"crawler":{"login":"admin","passwd":"admin"},"log":{"level":10},"sqlalchemy":{"test_uri":"postgresql:///jarr_test"}}' > ~/.config/jarr.test.json

script:
  - CONFIG_FILE=~/.config/jarr.test.json pipenv run nosetests tests/ -v --with-coverage --cover-package=jarr,jarr_common,jarr_crawler
  # ignoring aligning / line breaking non-sens
  - pycodestyle --ignore=E126,E127,E128,W503 jarr/ --exclude=jarr/migrations
  - pycodestyle --ignore=E126,E127,E128,W503 jarr_crawler/
  - pycodestyle --ignore=E126,E127,E128,W503 jarr_common/

after_success:
  - coveralls
